[build]
  # Commande de build pour Vite
  command = "npm run build"
  # Dossier de sortie après le build
  publish = "dist"

[build.environment]
  # Version de Node.js à utiliser
  NODE_VERSION = "18"

# Configuration pour les Single Page Applications (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    # Sécurité générale
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Permissions Policy pour limiter les fonctionnalités
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers spécifiques pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration pour les formulaires Netlify (si nécessaire plus tard)
[forms]
  settings = { error_template = "form-errors.html" }
